client_config_backend: settings
# client_config_file: client_secrets.json
client_config:
  client_id: blablabla.apps.googleusercontent.com
  client_secret: blablabla

save_credentials: True
save_credentials_backend: file
save_credentials_file: google_creds.txt

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file