client_config_backend: settings
client_config_file: client_secret.json
# client_config:
  # client_id: jibberjabber
  # client_secret: yourmothersadirtywhore

save_credentials: True
save_credentials_backend: file
save_credentials_file: google_creds.json
save_credentials_file: google_creds.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive